import json

import numpy as np
import pandas as pd
import pytest

from riverbrain.features import build_features, build_inputs
from riverbrain.model import clean_json, components, dumps, forecast, ols, predict
from riverbrain.outputs import do_saturation_mg_l, extrema, trend_ft_per_h

FEATS = ["T", "Tq", "HT", "HTq", "q", "q2", "qw", "sn"]
SPEC = dict(features=FEATS, tau=6, width=12, fast_tau=None, surge_lag=0)
TRUE = dict(const=-1.0, T=1.8, Tq=-0.5, HT=-0.3, HTq=0.2, q=0.01, q2=0.4, qw=0.05, sn=2.0)


def make_inputs(syn, noise=0.0):
    """Inputs whose stage is generated by the model itself (known coefficients)."""
    idx = syn["h"]
    inp = build_inputs(idx, stage15=syn["stage15"], bon=syn["bon"], wil5=syn["wil5"], pred6=syn["pred6"])
    f = build_features(inp, SPEC)
    y = predict(f, TRUE) + noise * syn["rng"].normal(0, 1, len(f))
    inp["stage"] = y
    return inp


def test_features_are_causal(synthetic):
    inp = make_inputs(synthetic)
    t = inp.index[900]
    a = build_features(inp, SPEC)
    changed = inp.copy()
    changed.loc[changed.index > t, ["bon", "wil", "stage"]] *= 3.0  # rewrite the future
    b = build_features(changed, SPEC)
    flow_cols = ["Tq", "HTq", "q", "q2", "qw"]
    pd.testing.assert_frame_equal(a.loc[:t, flow_cols], b.loc[:t, flow_cols])


def test_asof_equals_truncated_data(synthetic):
    """Hindcast truncation must behave exactly like data that simply ends at t0."""
    inp = make_inputs(synthetic)
    t0 = inp.index[900]
    a = build_features(inp, SPEC, asof=t0)
    trunc = inp.copy()
    trunc.loc[trunc.index > t0, ["bon", "wil", "surge", "stage"]] = np.nan
    b = build_features(trunc, SPEC)
    pd.testing.assert_frame_equal(a, b)


def test_ols_recovers_known_coefficients(synthetic):
    inp = make_inputs(synthetic, noise=0.02)
    f = build_features(inp, SPEC)
    coef, e, n = ols(f, FEATS)
    assert n > 1000 and e < 0.03
    for k in ("T", "HT", "qw", "sn"):
        assert coef[k] == pytest.approx(TRUE[k], rel=0.1, abs=0.05), k


def test_components_sum_to_model_and_attribution_closes(synthetic):
    inp = make_inputs(synthetic, noise=0.05)
    f = build_features(inp, SPEC)
    c = components(f, TRUE)
    parts = c[["tide", "bonneville", "willamette", "spring_neap", "const"]].sum(axis=1)
    ok = c["model"].notna()
    assert np.allclose(parts[ok], c["model"][ok])
    t1, t0 = c.index[1000], c.index[994]
    d = c.loc[t1] - c.loc[t0]
    assert d[["tide", "bonneville", "willamette", "spring_neap", "unexplained"]].sum() == pytest.approx(
        d["observed"], abs=1e-9)


def test_forecast_uses_only_past_flows(synthetic):
    inp = make_inputs(synthetic)
    t0 = inp.index[900]
    fc1 = forecast(inp, SPEC, TRUE, t0, 48, 24.0)
    changed = inp.copy()
    changed.loc[changed.index > t0, ["bon", "wil", "stage"]] += 100
    fc2 = forecast(changed, SPEC, TRUE, t0, 48, 24.0)
    pd.testing.assert_series_equal(fc1["forecast"], fc2["forecast"])
    assert fc1["lead_h"].iloc[0] == 0 and fc1["lead_h"].iloc[-1] == 48


def test_json_is_strict():
    s = dumps({"a": float("nan"), "b": float("inf"), "c": np.float64(1.5), "d": [np.int64(2)]})
    assert json.loads(s) == {"a": None, "b": None, "c": 1.5, "d": [2]}
    assert clean_json({"x": np.bool_(True)}) == {"x": True}


def test_do_saturation_matches_apha_table():
    # APHA Standard Methods table: 11.29 mg/L at 10 °C, 9.09 at 20 °C, 7.56 at 30 °C (1 atm, fresh water)
    assert do_saturation_mg_l([10, 20, 30]) == pytest.approx([11.29, 9.09, 7.56], abs=0.02)


def test_extrema_refines_peak_time():
    idx = pd.date_range("2026-01-01", periods=30, freq="h", tz="UTC")
    x = np.arange(30)
    s = pd.Series(np.cos(2 * np.pi * (x - 10.3) / 12.42), index=idx)  # true high at 10.3 h
    hi = next(e for e in extrema(s) if e["type"] == "high")
    t = pd.Timestamp(hi["time"])
    assert abs((t - idx[0]) / pd.Timedelta("1h") - 10.3) < 0.1
    assert hi["stage_ft"] == pytest.approx(1.0, abs=0.01)


def test_trend_tolerates_batched_usgs_readings():
    # Real case (2026-09-24): 13:00-13:45 not yet delivered; only 14:00 and 14:15 present
    idx = pd.to_datetime(["2026-09-24 12:45", "2026-09-24 14:00", "2026-09-24 14:15"], utc=True)
    s = pd.Series([3.11, 2.46, 2.32], index=idx)
    assert trend_ft_per_h(s, idx[-1]) == pytest.approx(-0.56, abs=0.01)
    assert trend_ft_per_h(s.iloc[-1:], idx[-1]) is None
